package com.Interface.common;  
import java.util.Date;
  
/**  
 * This code is generated by FreeMarker   
 */  
public class Param  
{  

    /********** attribute ***********/  
    private String userId="24744505";   
    private String accountStatus="NORMAL";   
    private String accountType="DEBIT_ACCOUNT";   
    private String currencyType="CNY";   
    private String balanceType="ACCOUNT_BALANCE";   
    private String name="test";   

    /********** constructors ***********/  
  
    /********** get/set ***********/  
    public String getUserId() {  
        return userId;  
    }  
  
    public void setUserId(String userId) {  
        this.userId = userId;  
    }  
      
    public String getAccountStatus() {  
        return accountStatus;  
    }  
  
    public void setAccountStatus(String accountStatus) {  
        this.accountStatus = accountStatus;  
    }  
      
    public String getAccountType() {  
        return accountType;  
    }  
  
    public void setAccountType(String accountType) {  
        this.accountType = accountType;  
    }  
      
    public String getCurrencyType() {  
        return currencyType;  
    }  
  
    public void setCurrencyType(String currencyType) {  
        this.currencyType = currencyType;  
    }  
      
    public String getBalanceType() {  
        return balanceType;  
    }  
  
    public void setBalanceType(String balanceType) {  
        this.balanceType = balanceType;  
    }  
      
    public String getName() {  
        return name;  
    }  
  
    public void setName(String name) {  
        this.name = name;  
    }  
      
}  